server.port=8080

# Configuración explícita de Base de Datos H2
spring.datasource.url=jdbc:h2:mem:hogarcalidodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Consola H2 requerida para revisión
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate y SQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true